server:
  port: 8081

spring:
  config:
    import: classpath:/application-secrets.yml
  application:
    name: "guitar-reflect"

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
